{% set name = "types-Jinja2" %}
{% set version = "2.11.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Jinja2-{{ version }}.tar.gz
  sha256: 10b97b5dc187e599e0b5707c4d1c5f11368f08b6e689677d4a0e0397300b7dbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-markupsafe

test:
  commands:
    - test -f $SP_DIR/jinja2-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Jinja2
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
